# Generated by Django 6.0.2 on 2026-03-09 22:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCanal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100, unique=True)),
                ('disponible', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acompañamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comienzo', models.DateTimeField(auto_now_add=True)),
                ('tiempo_estimado', models.DurationField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('max_tiempo_act', models.IntegerField(default=43200)),
                ('origen', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destino', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ACEPTADO', 'Aceptado por acompañante'), ('ASIGNADO', 'Confirmado por solicitante'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='buscando', max_length=20)),
                ('acompañante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompañamientos_aceptados', to='application.perfilusuario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompañamientos_solicitados', to='application.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaDeSuscripcion', models.DateField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('disponible', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravedad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='application.zona')),
            ],
        ),
    ]
