# Generated by Django 6.0.2 on 2026-03-24 11:36

import application.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='RegistroPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=225)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=2)),
                ('m1_acepto', models.BooleanField(null=True)),
                ('m2_acepto', models.BooleanField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caduca_en', models.DateTimeField(default=application.models.expiracion)),
                ('mujer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mujer_1', to='application.perfilusuario')),
                ('mujer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mujer_2', to='application.perfilusuario')),
            ],
        ),
    ]
