# Generated by Django 6.0.2 on 2026-04-06 10:08

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_perfilusuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompañamiento',
            name='caduca_en',
            field=models.DateTimeField(default=application.models.expiracion_acompañamiento),
        ),
    ]
