# Generated by Django 6.0.2 on 2026-04-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_acompañamiento_caduca_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompañamiento',
            name='hora_solicitada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
