# Generated by Django 6.0.2 on 2026-04-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_acompañamiento_hora_solicitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompañamiento',
            name='cancelado_por',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
