# Generated by Django 6.0.2 on 2026-04-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_acompañamiento_cancelado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoAcompañamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acompañamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='application.acompañamiento')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='application.perfilusuario')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('acompañamiento', 'candidato')},
            },
        ),
    ]
