# Generated by Django 6.0.2 on 2026-04-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_candidatoacompañamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompañamiento',
            name='hora_fin_estimada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acompañamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.acompañamiento')),
                ('valorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to='application.perfilusuario')),
                ('valorador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_dadas', to='application.perfilusuario')),
            ],
        ),
    ]
