# Generated by Django 6.0.2 on 2026-04-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_acompañamiento_hora_fin_estimada_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='acompañamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='application.acompañamiento'),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('acompañamiento', 'valorador')},
        ),
    ]
