# Generated by Django 6.0.2 on 2026-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_valoracion_acompañamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompañamiento',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ACEPTADO', 'Aceptado por acompañante'), ('ASIGNADO', 'Confirmado por solicitante'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='buscando', max_length=20),
        ),
    ]
