# Generated by Django 6.0.2 on 2026-04-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_incidencia_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Canal',
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
