# Generated by Django 6.0.2 on 2026-04-24 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_suscripcion_canal_remove_suscripcion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompañamiento',
            name='panico',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='acompañamiento',
            name='panico_activado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acompañamiento',
            name='tipo',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('FISICO', 'Físico')], default='FISICO', max_length=20),
        ),
    ]
